### ISSUE TITLE
Use shields.io for floobits status images

### ISSUE THREAD

**Issue by michaelsbradleyjr** [Floobits/issues#2]
### Proposal

Use [shields.io](http://shields.io/) for Floobits status images. That would allow them to share a consistent look with Travis CI badges, Gratipay (Gittip) badges, etc.
### Mockups

[![Floobits status](http://img.shields.io/badge/Floobits-info-lightgrey.svg?style=flat)](https://floobits.com/some/workspace/redirect)

[![Floobits status](http://img.shields.io/badge/Floobits-now%20coding-brightgreen.svg?style=flat)](https://floobits.com/some/workspace/redirect)

``` markdown
[![Floobits status](http://img.shields.io/badge/Floobits-info-lightgrey.svg?style=flat)](https://floobits.com/some/workspace/redirect)

[![Floobits status](http://img.shields.io/badge/Floobits-now%20coding-brightgreen.svg?style=flat)](https://floobits.com/some/workspace/redirect)
```

**Comment by ggreer** [comment]
Thank you for the suggestion. We've implemented and deployed new badges.
