### ISSUE TITLE
Feature: A badge to invite pairing on a github/gitlab project

### ISSUE THREAD

**Issue by asfaltboy** [Floobits/issues#6]
For example the badge can link to a project/space such as https://floobits.com/asfaltboy/test_ws/info. 

The badge "markup/code" can be auto-generated for an imported project for easy copy paste into a README file.

**Comment by ggreer** [comment]
If you go to the workspace's settings and look at the "Status image" section, there should be markdown and html for a badge. If someone is editing the workspace, it will be green and the link will redirect to the web editor. If nobody is editing, it will be gray and redirect to the workspace info page.
