### ISSUE TITLE
File Hotlinks

### ISSUE THREAD

**Issue by Tcll** [Floobits/issues#7]
Ive just started a recent workspace to work on my forum plugins more efficiently...
I'm not sure if it's already possible to get the hotlinks to reference in <script> tags, but if not, it's something that would really be useful. :)

**Comment by ggreer** [comment]
Stick `/browse/` on the end of a workspace URL to get a static HTML page with links to individual files. Eg: https://floobits.com/ggreer/ag/browse

For each file in that browser, you should see a link to the raw document. eg: https://floobits.com/ggreer/ag/raw/src/search.c

Please don't use this for anything important. It's rather slow. Depending on cache headers, you may get a stale version of the file.

**Comment by Tcll** [comment]
Thanks :)
