### ISSUE TITLE
[request] give free users at least 1 private workspace

### ISSUE THREAD

**Issue by Tcll** [Floobits/issues#8]
if they want more, let them pay for more :)

I have no money and absolutely need a private workspace.

I don't want just anyone to simply look at my profile page and get the source to my forum plugins...
I don't think ProBoards support would be too happy with that either...

so please, just give free users one private workspace.
once they get off the ground a bit, by donations or whatever, they can buy whatever more they need. ;)

**Comment by ggreer** [comment]
Sorry, no.
